"""teams meets events ticker updates

Revision ID: 165d8424beea
Revises: 938b340970d9
Create Date: 2026-07-21 21:14:13.523088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165d8424beea'
down_revision: Union[str, Sequence[str], None] = '938b340970d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('home_team_id', sa.UUID(), nullable=True),
    sa.Column('away_team_id', sa.UUID(), nullable=True),
    sa.Column('meet_type', sa.Enum('dual', 'championship', name='meet_type'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'live', 'completed', name='meet_status'), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meet_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', name='meet_event_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meet_events_meet_id'), 'meet_events', ['meet_id'], unique=False)
    op.create_table('ticker_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meet_id', sa.UUID(), nullable=False),
    sa.Column('meet_event_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meet_event_id'], ['meet_events.id'], ),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_updates_meet_id'), 'ticker_updates', ['meet_id'], unique=False)
    op.add_column('market_groups', sa.Column('meet_id', sa.UUID(), nullable=True))
    op.add_column('market_groups', sa.Column('meet_event_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'market_groups', 'meets', ['meet_id'], ['id'])
    op.create_foreign_key(None, 'market_groups', 'meet_events', ['meet_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market_groups', type_='foreignkey')
    op.drop_constraint(None, 'market_groups', type_='foreignkey')
    op.drop_column('market_groups', 'meet_event_id')
    op.drop_column('market_groups', 'meet_id')
    op.drop_index(op.f('ix_ticker_updates_meet_id'), table_name='ticker_updates')
    op.drop_table('ticker_updates')
    op.drop_index(op.f('ix_meet_events_meet_id'), table_name='meet_events')
    op.drop_table('meet_events')
    op.drop_table('meets')
    op.drop_table('teams')
    # ### end Alembic commands ###
