"""markets orders trades positions

Revision ID: 938b340970d9
Revises: 580a22aa0ebd
Create Date: 2026-07-21 20:41:32.955989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938b340970d9'
down_revision: Union[str, Sequence[str], None] = '580a22aa0ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'resolved', name='market_group_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_group_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('open', 'paused', 'closed', 'resolved', name='market_status'), nullable=False),
    sa.Column('resolved_outcome', sa.Enum('yes', 'no', name='market_outcome'), nullable=True),
    sa.Column('close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_group_id'], ['market_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_market_group_id'), 'markets', ['market_group_id'], unique=False)
    op.create_index('ix_markets_one_winner_per_group', 'markets', ['market_group_id'], unique=True, postgresql_where="resolved_outcome = 'yes'")
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.Enum('yes', 'no', name='order_side'), nullable=False),
    sa.Column('action', sa.Enum('buy', 'sell', name='order_action'), nullable=False),
    sa.Column('order_type', sa.Enum('limit', 'market', name='order_type'), nullable=False),
    sa.Column('time_in_force', sa.Enum('gtc', 'ioc', 'fok', name='order_time_in_force'), nullable=False),
    sa.Column('limit_price_cents', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'partially_filled', 'filled', 'cancelled', 'not_found', name='order_status'), nullable=False),
    sa.Column('collateral_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_market_id'), 'orders', ['market_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('net_yes_quantity', sa.Integer(), nullable=False),
    sa.Column('avg_cost_cents', sa.Integer(), nullable=False),
    sa.Column('realized_pnl_cents', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'market_id', name='uq_positions_user_market')
    )
    op.create_index(op.f('ix_positions_market_id'), 'positions', ['market_id'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('buy_order_id', sa.UUID(), nullable=False),
    sa.Column('sell_order_id', sa.UUID(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buy_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['sell_order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_market_id'), 'trades', ['market_id'], unique=False)
    op.drop_constraint(op.f('accounts_owner_id_fkey'), 'accounts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('accounts_owner_id_fkey'), 'accounts', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_trades_market_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_market_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_market_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_markets_one_winner_per_group', table_name='markets', postgresql_where="resolved_outcome = 'yes'")
    op.drop_index(op.f('ix_markets_market_group_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_table('market_groups')
    # ### end Alembic commands ###
